---
- hosts: ansible
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t regapp:latest .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag abhi2305/regapp:latest

  - name: push image on to dockerhub
    command: docker push abhi2305/regapp:latest

  - name: remove docker images form ansible server
    command: docker rmi regapp:latest abhi2305/regapp:latest
    ignore_errors: yes
