apiVersion: apps/v1 
kind: Deployment
metadata:
  name: regapp-deployment
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp-cont
        image: abhi2305/regapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
